/**
 * This class is generated by jOOQ
 */
package com.pretech.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tabletestidm1Record extends org.jooq.impl.TableRecordImpl<com.pretech.jooq.tables.records.Tabletestidm1Record> implements org.jooq.Record4<java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1296117135;

	/**
	 * Setter for <code>basetestidm.tabletestidm1.col1Idm1</code>.
	 */
	public void setCol1idm1(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>basetestidm.tabletestidm1.col1Idm1</code>.
	 */
	public java.lang.String getCol1idm1() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>basetestidm.tabletestidm1.col2Idm1</code>.
	 */
	public void setCol2idm1(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>basetestidm.tabletestidm1.col2Idm1</code>.
	 */
	public java.lang.String getCol2idm1() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>basetestidm.tabletestidm1.col3Idm1</code>.
	 */
	public void setCol3idm1(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>basetestidm.tabletestidm1.col3Idm1</code>.
	 */
	public java.lang.String getCol3idm1() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>basetestidm.tabletestidm1.col4Idm1</code>.
	 */
	public void setCol4idm1(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>basetestidm.tabletestidm1.col4Idm1</code>.
	 */
	public java.lang.String getCol4idm1() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.String> field1() {
		return com.pretech.jooq.tables.Tabletestidm1.TABLETESTIDM1.COL1IDM1;
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.String> field2() {
		return com.pretech.jooq.tables.Tabletestidm1.TABLETESTIDM1.COL2IDM1;
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.String> field3() {
		return com.pretech.jooq.tables.Tabletestidm1.TABLETESTIDM1.COL3IDM1;
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.String> field4() {
		return com.pretech.jooq.tables.Tabletestidm1.TABLETESTIDM1.COL4IDM1;
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.String value1() {
		return getCol1idm1();
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.String value2() {
		return getCol2idm1();
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.String value3() {
		return getCol3idm1();
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.String value4() {
		return getCol4idm1();
	}

	/**
	 * {@inheritDoc}
	 */
	public Tabletestidm1Record value1(java.lang.String value) {
		setCol1idm1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	public Tabletestidm1Record value2(java.lang.String value) {
		setCol2idm1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	
	public Tabletestidm1Record value3(java.lang.String value) {
		setCol3idm1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	
	public Tabletestidm1Record value4(java.lang.String value) {
		setCol4idm1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	
	public Tabletestidm1Record values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Tabletestidm1Record
	 */
	public Tabletestidm1Record() {
		super(com.pretech.jooq.tables.Tabletestidm1.TABLETESTIDM1);
	}

	/**
	 * Create a detached, initialised Tabletestidm1Record
	 */
	public Tabletestidm1Record(java.lang.String col1idm1, java.lang.String col2idm1, java.lang.String col3idm1, java.lang.String col4idm1) {
		super(com.pretech.jooq.tables.Tabletestidm1.TABLETESTIDM1);

		setValue(0, col1idm1);
		setValue(1, col2idm1);
		setValue(2, col3idm1);
		setValue(3, col4idm1);
	}
}
