/**
 * This class is generated by jOOQ
 */
package com.pretech.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tabletestidm2Record extends org.jooq.impl.TableRecordImpl<com.pretech.jooq.tables.records.Tabletestidm2Record> implements org.jooq.Record2<java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1559108270;

	/**
	 * Setter for <code>basetestidm.tabletestidm2.col1idm2</code>.
	 */
	public void setCol1idm2(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>basetestidm.tabletestidm2.col1idm2</code>.
	 */
	public java.lang.String getCol1idm2() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>basetestidm.tabletestidm2.col2idm2</code>.
	 */
	public void setCol2idm2(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>basetestidm.tabletestidm2.col2idm2</code>.
	 */
	public java.lang.String getCol2idm2() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	
	public org.jooq.Row2<java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	
	public org.jooq.Row2<java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	
	public org.jooq.Field<java.lang.String> field1() {
		return com.pretech.jooq.tables.Tabletestidm2.TABLETESTIDM2.COL1IDM2;
	}

	/**
	 * {@inheritDoc}
	 */
	
	public org.jooq.Field<java.lang.String> field2() {
		return com.pretech.jooq.tables.Tabletestidm2.TABLETESTIDM2.COL2IDM2;
	}

	/**
	 * {@inheritDoc}
	 */
	
	public java.lang.String value1() {
		return getCol1idm2();
	}

	/**
	 * {@inheritDoc}
	 */
	
	public java.lang.String value2() {
		return getCol2idm2();
	}

	/**
	 * {@inheritDoc}
	 */
	
	public Tabletestidm2Record value1(java.lang.String value) {
		setCol1idm2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	
	public Tabletestidm2Record value2(java.lang.String value) {
		setCol2idm2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	
	public Tabletestidm2Record values(java.lang.String value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Tabletestidm2Record
	 */
	public Tabletestidm2Record() {
		super(com.pretech.jooq.tables.Tabletestidm2.TABLETESTIDM2);
	}

	/**
	 * Create a detached, initialised Tabletestidm2Record
	 */
	public Tabletestidm2Record(java.lang.String col1idm2, java.lang.String col2idm2) {
		super(com.pretech.jooq.tables.Tabletestidm2.TABLETESTIDM2);

		setValue(0, col1idm2);
		setValue(1, col2idm2);
	}
}
