/**
 * This class is generated by jOOQ
 */
package com.pretech.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tabletestidm1 extends org.jooq.impl.TableImpl<com.pretech.jooq.tables.records.Tabletestidm1Record> {

	private static final long serialVersionUID = 493461661;

	/**
	 * The singleton instance of <code>basetestidm.tabletestidm1</code>
	 */
	public static final com.pretech.jooq.tables.Tabletestidm1 TABLETESTIDM1 = new com.pretech.jooq.tables.Tabletestidm1();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.pretech.jooq.tables.records.Tabletestidm1Record> getRecordType() {
		return com.pretech.jooq.tables.records.Tabletestidm1Record.class;
	}

	/**
	 * The column <code>basetestidm.tabletestidm1.col1Idm1</code>.
	 */
	public final org.jooq.TableField<com.pretech.jooq.tables.records.Tabletestidm1Record, java.lang.String> COL1IDM1 = createField("col1Idm1", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>basetestidm.tabletestidm1.col2Idm1</code>.
	 */
	public final org.jooq.TableField<com.pretech.jooq.tables.records.Tabletestidm1Record, java.lang.String> COL2IDM1 = createField("col2Idm1", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>basetestidm.tabletestidm1.col3Idm1</code>.
	 */
	public final org.jooq.TableField<com.pretech.jooq.tables.records.Tabletestidm1Record, java.lang.String> COL3IDM1 = createField("col3Idm1", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>basetestidm.tabletestidm1.col4Idm1</code>.
	 */
	public final org.jooq.TableField<com.pretech.jooq.tables.records.Tabletestidm1Record, java.lang.String> COL4IDM1 = createField("col4Idm1", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>basetestidm.tabletestidm1</code> table reference
	 */
	public Tabletestidm1() {
		this("tabletestidm1", null);
	}

	/**
	 * Create an aliased <code>basetestidm.tabletestidm1</code> table reference
	 */
	public Tabletestidm1(java.lang.String alias) {
		this(alias, com.pretech.jooq.tables.Tabletestidm1.TABLETESTIDM1);
	}

	private Tabletestidm1(java.lang.String alias, org.jooq.Table<com.pretech.jooq.tables.records.Tabletestidm1Record> aliased) {
		this(alias, aliased, null);
	}

	private Tabletestidm1(java.lang.String alias, org.jooq.Table<com.pretech.jooq.tables.records.Tabletestidm1Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.pretech.jooq.Basetestidm.BASETESTIDM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.pretech.jooq.tables.Tabletestidm1 as(java.lang.String alias) {
		return new com.pretech.jooq.tables.Tabletestidm1(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.pretech.jooq.tables.Tabletestidm1 rename(java.lang.String name) {
		return new com.pretech.jooq.tables.Tabletestidm1(name, null);
	}
}
