/**
 * This class is generated by jOOQ
 */
package com.pretech.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tabletestidm2 extends org.jooq.impl.TableImpl<com.pretech.jooq.tables.records.Tabletestidm2Record> {

	private static final long serialVersionUID = -1944130811;

	/**
	 * The singleton instance of <code>basetestidm.tabletestidm2</code>
	 */
	public static final com.pretech.jooq.tables.Tabletestidm2 TABLETESTIDM2 = new com.pretech.jooq.tables.Tabletestidm2();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.pretech.jooq.tables.records.Tabletestidm2Record> getRecordType() {
		return com.pretech.jooq.tables.records.Tabletestidm2Record.class;
	}

	/**
	 * The column <code>basetestidm.tabletestidm2.col1idm2</code>.
	 */
	public final org.jooq.TableField<com.pretech.jooq.tables.records.Tabletestidm2Record, java.lang.String> COL1IDM2 = createField("col1idm2", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>basetestidm.tabletestidm2.col2idm2</code>.
	 */
	public final org.jooq.TableField<com.pretech.jooq.tables.records.Tabletestidm2Record, java.lang.String> COL2IDM2 = createField("col2idm2", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>basetestidm.tabletestidm2</code> table reference
	 */
	public Tabletestidm2() {
		this("tabletestidm2", null);
	}

	/**
	 * Create an aliased <code>basetestidm.tabletestidm2</code> table reference
	 */
	public Tabletestidm2(java.lang.String alias) {
		this(alias, com.pretech.jooq.tables.Tabletestidm2.TABLETESTIDM2);
	}

	private Tabletestidm2(java.lang.String alias, org.jooq.Table<com.pretech.jooq.tables.records.Tabletestidm2Record> aliased) {
		this(alias, aliased, null);
	}

	private Tabletestidm2(java.lang.String alias, org.jooq.Table<com.pretech.jooq.tables.records.Tabletestidm2Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.pretech.jooq.Basetestidm.BASETESTIDM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.pretech.jooq.tables.Tabletestidm2 as(java.lang.String alias) {
		return new com.pretech.jooq.tables.Tabletestidm2(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.pretech.jooq.tables.Tabletestidm2 rename(java.lang.String name) {
		return new com.pretech.jooq.tables.Tabletestidm2(name, null);
	}
}
