/**
 * This class is generated by jOOQ
 */
package com.pretech.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Basetestidm extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1262643929;

	/**
	 * The singleton instance of <code>basetestidm</code>
	 */
	public static final Basetestidm BASETESTIDM = new Basetestidm();

	/**
	 * No further instances allowed
	 */
	private Basetestidm() {
		super("basetestidm");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.pretech.jooq.tables.Tabletestidm1.TABLETESTIDM1,
			com.pretech.jooq.tables.Tabletestidm2.TABLETESTIDM2);
	}
}
