/**
 * This class is generated by jOOQ
 */
package com.pretech.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in basetestidm
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table basetestidm.tabletestidm1
	 */
	public static final com.pretech.jooq.tables.Tabletestidm1 TABLETESTIDM1 = com.pretech.jooq.tables.Tabletestidm1.TABLETESTIDM1;

	/**
	 * The table basetestidm.tabletestidm2
	 */
	public static final com.pretech.jooq.tables.Tabletestidm2 TABLETESTIDM2 = com.pretech.jooq.tables.Tabletestidm2.TABLETESTIDM2;
}
